// <auto-generated />
namespace TokenAuth.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addmgrtiinitilMigrtion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmgrtiinitilMigrtion));
        
        string IMigrationMetadata.Id
        {
            get { return "202402172112235_add-mgrti'initilMigrtion'"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
